#!/bin/bash
./lpdtsp.e -e -i in/gr_kinder4_lpd   -o out/gr_kinder4_lpd.EXACT.out
./lpdtsp.e -e -i in/gr_ulysses23_lpd -o out/gr_ulysses23_lpd.EXACT.out
./lpdtsp.e -e -i in/gr_berlin51_lpd  -o out/gr_berlin51_lpd.EXACT.out
./lpdtsp.e -e -i in/gr_att47e_lpd  -o out/gr_att47e_lpd.EXACT.out
./lpdtsp.e -e -i in/gr_d197e_lpd  -o out/gr_d197e_lpd.EXACT.out
