#!/bin/bash
./lpdtsp.e -c -g -i in/gr_kinder4_lpd   -o out/gr_kinder4_lpd.CONSTR_HEUR.out
read -p 'Press ENTER key...'
./lpdtsp.e -c -g -i in/gr_ulysses23_lpd -o out/gr_ulysses23_lpd.CONSTR_HEUR.out
read -p 'Press ENTER key...'
./lpdtsp.e -c -g -i in/gr_berlin51_lpd  -o out/gr_berlin51_lpd.CONSTR_HEUR.out
read -p 'Press ENTER key...'
